shallow_clone: true
# version format
version: 1.0.{build}
# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

cache:
  - Sigma\Sigma.Website\bower_components -> Sigma\Sigma.Website\bower.json
  - Sigma\Sigma.Website\node_modules -> Sigma\Sigma.Website\package.json

install:
  - npm install -g grunt-cli  1> nul

before_build:
  - ps: .\CreateBuildTxt.ps1
  - cmd: |
          cd Sigma\Sigma.Website
          npm install
          grunt
          nuget restore
  - nuget restore
  
build:
  publish_wap: true

#Deployment configuration
deploy:
- provider: WebDeploy
  server: sigma.scm.azurewebsites.net:443/msdeploy.axd?site=sigma
  name: sigma
  website: sigma
  username: $sigma
  password:
    secure: IhaZvK00JIzvrUW+ljpzeOMh5AfnLiXWc6LsT4IwMmHKS5B8hggnq+WeWZcMBgEo++2Pa+texX1Q+ytPZhoSIQ==
  ntlm: false
  remove_files: true
  app_offline: false
  artifact: Sigma.Website
  on:
    branch: master

notifications:
  - provider: Slack
    auth_token:
      secure: xoxp-33771451379-33820609287-55826048132-4f117727bc
    channel: '#sigma-dev'
    on_build_success: true
    on_build_failure: true