shallow_clone: true
# version format
version: 1.1.{build}
# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

cache:
  - packages -> **\packages.config
  - Sigma.Website\bower_components -> Sigma.Website\bower.json
  - Sigma.Website\node_modules -> Sigma.Website\package.json

install:
  - npm install -g grunt-cli  1> nul

before_build:
  - ps: .\CreateBuildTxt.ps1  
  - nuget restore
  - cmd: |
          cd Sigma.Website
          npm install
          grunt
          cd ..

build:
  publish_wap: true

#Deployment configuration
deploy:
- provider: WebDeploy
  server: https://sigma.scm.azurewebsites.net:443/msdeploy.axd?site=sigma
  website: sigma
  username: $sigma
  password:
    secure: MASVXvz2HYucpe3uT2hvHzftMRYUInfhktp8gyiLKPCPu0WKUTaFte2DQq9EFHJnkMRYp2nFb/9RTFvp0TDyng==
  ntlm: false
  remove_files: true
  app_offline: false
  artifact: Sigma.Website
  on:
    branch: master

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: '#sigma-dev'
    on_build_success: true
    on_build_failure: true